# Generated by Django 4.2 on 2026-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_auto_20210322_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
